site_name: RATHNA SCHOOLS
site_url: https://learnjs.rathnaschools.com
site_author: RATHINAVELKUMAR M
site_description: >-
  An interactive site to learn Javascript from scratch

nav:
    - Javascript Introduction: index.md
    - Javascript Data Types: js_data_types.md
    - Javascript Comments: js_comments.md
    - Javascript Variables: js_variables.md

theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-##########
  social:
  - icon: fontawesome/solid/globe
    link: https://www.rathnaschools.com